name: Frontier RPC Tests

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [main, francisco-evm_support]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Configure git for Cargo
        run: |
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Install deps
        run: sudo apt -y install protobuf-compiler

      - name: Install & display rust toolchain
        run: rustup show

      - name: Check targets are installed correctly
        run: rustup target list --installed

      - name: Build Centrum
        run: cargo build --release --locked

      - name: Clone frontier tests
        run: git clone https://github.com/Abstracted-Labs/frontier-tests.git --depth 1

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: frontier-tests/package-lock.json

      - name: Install dependencies
        working-directory: frontier-tests
        run: npm install --frozen

      - name: Build contracts
        working-directory: frontier-tests
        run: npm run build

      - name: Run frontier RPC tests
        working-directory: frontier-tests
        run: npm run test
        env:
          BINARY_PATH: ${{ github.workspace }}/target/release